FROM --platform=linux/amd64 php:8.2-apache

RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip && docker-php-ext-install pdo pdo_mysql mysqli

RUN pecl install redis && docker-php-ext-enable redis

RUN a2enmod rewrite headers

COPY apache-site.conf /etc/apache2/sites-available/000-default.conf

EXPOSE 80
